@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":UniCashParser" as UniCashParser LOGIC_COLOR
participant ":ClearTransactionsCommandParser" as ClearTransactionsCommandParser LOGIC_COLOR
participant "d:ClearTransactionsCommand" as ClearTransactionsCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("clear_transactions")
activate LogicManager

LogicManager -> UniCashParser : parseCommand("clear_transactions")
activate UniCashParser

create ClearTransactionsCommandParser
UniCashParser -> ClearTransactionsCommandParser
activate ClearTransactionsCommandParser

ClearTransactionsCommandParser --> UniCashParser
deactivate ClearTransactionsCommandParser

UniCashParser -> ClearTransactionsCommandParser : parse("")
activate ClearTransactionsCommandParser

create ClearTransactionsCommand
ClearTransactionsCommandParser -> ClearTransactionsCommand
activate ClearTransactionsCommand

ClearTransactionsCommand --> ClearTransactionsCommandParser :
deactivate ClearTransactionsCommand

ClearTransactionsCommandParser --> UniCashParser :
deactivate ClearTransactionsCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ClearTransactionsCommandParser -[hidden]-> UniCashParser
destroy ClearTransactionsCommandParser

UniCashParser --> LogicManager :
deactivate UniCashParser

LogicManager -> ClearTransactionsCommand : execute(model)
activate ClearTransactionsCommand

ClearTransactionsCommand -> Model : setUniCash(new UniCash())
activate Model

Model --> ClearTransactionsCommand
deactivate Model

create CommandResult
ClearTransactionsCommand -> CommandResult
activate CommandResult

CommandResult --> ClearTransactionsCommand
deactivate CommandResult

ClearTransactionsCommand --> LogicManager : command result
deactivate ClearTransactionsCommand

[<--LogicManager
deactivate LogicManager
@enduml
