@startuml

skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start

: User enters get command;

if () then ([else])
  :Parse exception thrown;
  stop
else ([command argument is a valid number])
  :Transaction successfully retrieved ;
endif


stop

@enduml
