@startuml

skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start

: User enters reset_unicash command;

if () then ([command followed with trailing characters])
  :Parse exception thrown;
  stop

else ([else])
  :UniCa$h successfully reset;

endif

stop

@enduml
